name: Keep Backend Awake

on:
  schedule:
    # Run every 4 minutes
    - cron: '*/2 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping /health
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://project-pry1.onrender.com/health
