name: Daily Codeforces Sync and Reminder

on:
  schedule:
    - cron: '23 19 * * *' # 12:53 AM IST
  workflow_dispatch:       # For manual testing

jobs:
  run-daily-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Call /sync-all-students
        run: |
          curl -X POST https://project-pry1.onrender.com/api/sync-all-students

      - name: Call /send-inactivity-reminders
        run: |
          curl -X POST https://project-pry1.onrender.com/api/send-inactivity-reminders
